DigitalSign.Web/Controllers/NotificationController.cs
using DigitalSign.Utilities;
using DigitalSign.ViewModels;
using DigitalSign.ViewModels.Master.Document;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using RestSharp;

namespace DigitalSign.Web.Controllers
{
	public class NotificationController : Controller
	{
		string url = $"{ApiUrl.Master}Notification/";

		public IActionResult GetAll()
		{
			if (ClaimHelper.CheckSession)
			{
				ViewBag.Username = ClaimHelper.UserName;
				ViewBag.Rolename = ClaimHelper.RoleName;
				var notification = ClaimHelper.GetNotification(ClaimHelper.LoginID);
				ViewBag.Notification = notification;
				int counter = notification.Where(a => a.ReadDate == null).Count();
				ViewBag.HitungCounter = counter;
				return View("NotificationAll", notification);
			}
			else
			{
				return RedirectToAction("SignIn", "Auth");
			}
		}

		public async Task<JsonResult> ReadNotification(int notifID)
		{
			int userID = ClaimHelper.LoginID;
			var jsonViewModel = new AjaxViewModel();
			var endpoint = url + $"ReadNotification?notifID={notifID}&userID={userID}";
			var result = Utilities.RestAPIHelper<ProcessResult>.Submit("", Method.GET, endpoint, Request);
			jsonViewModel.SetValues(result.isSucceed, result.value, result.message);
			return Json(jsonViewModel);
		}

		public async Task<JsonResult> DeleteNotification(int notifID)
		{
			string username = ClaimHelper.UserName;
			var jsonViewModel = new AjaxViewModel();
			var endpoint = url + $"DeleteNotification?notifID={notifID}&username={username}";
			var result = Utilities.RestAPIHelper<ProcessResult>.Submit("", Method.GET, endpoint, Request);
			jsonViewModel.SetValues(result.isSucceed, result.value, result.message);
			return Json(jsonViewModel);
		}

		public IActionResult WebHook(string request_id, bool success, string signer, string? signer_next, string? url)
		{
			var webHook = new CallbackSigningViewModel()
			{
				request_id = request_id,
				success	= success,
				signer= signer,
				signer_next = signer_next,
				url = url
			};
			var json = JsonConvert.SerializeObject(webHook);
			var endpoint = $"{ApiUrl.Master}Notification/WebHook";
			var result = Utilities.RestAPIHelper<ProcessResult>.Submit(json, Method.POST, endpoint);
			return Ok(result);
		}

	}
}

DigitalSign.Web/Views/Notification/NotificationAll.cshtml
@model IEnumerable<DigitalSign.ViewModels.Master.Notification.NotificationViewModel>
@{
	ViewData["Title"] = "Notification All";
}

<div class="container notif-all">
	@{
		
		foreach (var item in Model)
		{
				<a class="d-flex align-items-center shadow-lg rounded mb-2 p-3 text-decoration-none text-dark" id="@item.ID" style="cursor:pointer;background-color: @(item.ReadDate == null? "#CDFFCA" : "#FFF")">
					<div class="mr-3">
						<input type="hidden" value="@item.RedirectTo">
						<div class="icon-circle @(item.UserID != null? "bg-primary" : "bg-success")">
							<i class="fa fa-@(item.Icon) text-white"></i>
						</div>
					</div>
					<div class="mr-2">
						<div class="small text-dark-500">@item.CreateDate.ToString("dd MMM yyyy hh:mm")</div>
						<span class="font-weight-bold">@item.Title</span>
						<p class="mb-0">@item.Detail</p>
					</div>
					<div class="ml-auto">
						<button class="btn btn-danger btn-sm"> <i class="fa fa-trash text-white"></i></button>
					</div>
				</a>
		}

		if (Model.Count() <= 0)
		{
				<div class="d-flex align-items-center shadow-lg rounded mb-2 p-3 text-decoration-none text-dark bg-white">
					<p class="mb-0">There are no notifications to display</p>
				</div>
		}

	}
</div>


<script>
	const allNotif = document.querySelectorAll('.notif-all > a');
	allNotif.forEach(function(e){
		const input = e.querySelector('input');
		if(input != undefined){
			const endpoint = input.value;
			
			e.addEventListener('click',function(e){
				e.preventDefault();
				showProgress();
				const id = $(this).attr('id');
				
				$.ajax({
					type: "GET",
					data: {
						notifID : id
					},
					url: `@Url.Action("ReadNotification","Notification")`,
					success: function(result) {
						hideProgress();
						if (result.isSucceed) {
							window.location = "../"+endpoint;
						}
						else {
							location.reload();
						}
					},
					error: function(err) {
					}
				});
			})
			
			e.querySelector('button').addEventListener('click',function(e){
				e.preventDefault();
				e.stopPropagation();
				showProgress();
				const id = $(this).parent().parent().attr('id');
				//console.log(id);
				$.ajax({
					type: "GET",
					data: {
						notifID : id
					},
					url: `@Url.Action("DeleteNotification","Notification")`,
					success: function(result) {
						hideProgress();
						if (result.isSucceed) {
							swal("success!", result.Message, "success");
							setTimeout(function(){
								location.reload();
							},2000);
							
						}
						else {
							swal("Failed!", result.Message, "error");
							setTimeout(function(){
								location.reload();
							},2000);
						}
					},
					error: function(err) {
					}
				});
			})
		}
			
	})
</script>