DigitalSign.Web/Controllers/DocumentCategoryController.cs
using DigitalSign.Utilities;
using DigitalSign.ViewModels.Master.Role;
using DigitalSign.ViewModels;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using RestSharp;
using System.Security.Policy;
using DigitalSign.ViewModels.Master.Document;

namespace DigitalSign.Web.Controllers
{
    public class DocumentCategoryController : Controller
    {
        string _url = $"{ApiUrl.Master}DocumentCategory";
        public IActionResult Index()
        {
            if (ClaimHelper.CheckSession)
            {
                ViewBag.Username = ClaimHelper.UserName;
                ViewBag.Rolename = ClaimHelper.RoleName;
                var notification = ClaimHelper.GetNotification(ClaimHelper.LoginID);
                ViewBag.Notification = notification;
                int counter = notification.Where(a => a.ReadDate == null).Count();
                ViewBag.HitungCounter = counter;
                return View();
            }
            else
            {
                return RedirectToAction("SignIn", "Auth");
            }
        }

        [HttpPost]
        public JsonResult GetList([DataSourceRequest] DataSourceRequest request)
        {
            var endpoint = $"{_url}/GetAll";
            var viewModel = RestAPIHelper<List<DocumentCategoryViewModel>>.Submit("", Method.GET, endpoint, Request);
            var filter = viewModel.ToDataSourceResult(request);
            return Json(filter);
        }

        [HttpGet]
        public ActionResult Create()
        {
            var model = new DocumentCategoryViewModel();
            return PartialView("CreateEdit", model);
        }

        [HttpPost]
        public ActionResult CreateEdit(DocumentCategoryViewModel model)
        {
            var jsonViewModel = new AjaxViewModel();
            if (ModelState.IsValid)
            {
                try
                {
                    var currentUser = ClaimHelper.UserName;
                    string json = JsonConvert.SerializeObject(model);

                    var endpoint = $"{_url}/AddEditDocumentCategory?currentUser={currentUser}";
                    var content = Utilities.RestAPIHelper<ProcessResult>.Submit(json, Method.POST, endpoint, Request);
                    if (content != null)
                    {
                        jsonViewModel.SetValues(content.isSucceed, null, content.message);
                    }
                    else
                    {
                        jsonViewModel.SetValues(false, null, "Save Failed");
                    }
                }
                catch (Exception ex)
                {
                    jsonViewModel.SetValues(false, null, "Failed Message : " + ex.Message);
                }
                return Json(jsonViewModel);
            }
            var validationMessages = Utilities.ValidationHelper.GetValidationMessage(ModelState);
            jsonViewModel.SetValues(false, validationMessages, "");
            return Json(jsonViewModel);

        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var jsonViewModel = new AjaxViewModel();
            var model = new DocumentCategoryViewModel();
            try
            {
                var endpoint = $"{_url}/GetById?id={id}";
                model = Utilities.RestAPIHelper<DocumentCategoryViewModel>.Submit("", Method.GET, endpoint, Request);
            }
            catch (Exception ex)
            {
                jsonViewModel.SetValues(false, null, "Failed Message : " + ex.Message);
            }
            return PartialView("CreateEdit", model);
        }

        public ActionResult Delete(int id)
        {
            var ajaxViewModel = new AjaxViewModel();
            try
            {
                string json = JsonConvert.SerializeObject(id);
                var endpoint = $"{_url}/Delete?id={id}&currentUser={ClaimHelper.UserName}";
                var delete = Utilities.RestAPIHelper<AjaxViewModel>.Submit("", Method.DELETE, endpoint, Request);
                ajaxViewModel.SetValues(delete.isSucceed, null, delete.Message);
            }
            catch (Exception ex)
            {
                ajaxViewModel.SetValues(false, null, "Failed Message : " + ex.Message);
            }
            return Json(ajaxViewModel);
        }
    }
}

DigitalSign.Web/Views/DocumentCategory/CreateEdit.cshtml
@using Kendo.Mvc.UI
@model DigitalSign.ViewModels.Master.Document.DocumentCategoryViewModel

@using (Html.BeginForm(null, null, FormMethod.Post, new { id = "frm", name = "frm" }))
{
    <table class="table">
        @Html.HiddenFor(m => m.ID)
        <tr>
            <td>@Html.LabelFor(m => m.CategoryName)</td>
            <td>
                @(Html.Kendo().TextBoxFor(m => m.CategoryName).HtmlAttributes(new {@class="form-control", style = "width:200px", maxlength = "50" }))
                @Html.ValidationMessageFor(m => m.CategoryName)
            </td>
        </tr>
        <tr>
            <td>@Html.LabelFor(m => m.CategoryDescription)</td>
            <td>@(Html.Kendo().TextAreaFor(m => m.CategoryDescription).HtmlAttributes(new {@class="form-control", style="width:200px; height:80px;", maxlength="100" }))
        </tr>
    </table>

    <br />

    <div class="col-md-5">
        <button type="submit" id="btnSave" class="btn btn-success">
            <span class="glyphicon glyphicon-ok-circle" aria-hidden="true"></span>  Save
        </button>
        <a href="cancel" id="btnCancel" class="btn btn-danger">
            <span class="glyphicon glyphicon-remove-circle" aria-hidden="true"></span>  Cancel
        </a>
    </div>
}

<script type="text/javascript">
    $("#btnSave").click(function (e) {
        e.preventDefault();
        showProgress();
        var url = "@Url.Action("CreateEdit", "DocumentCategory")";

        $.ajax({
            type: "POST",
            data: $("#frm").serialize(),
            //     async: false,
            url: url,
            success: function (result) {

                if (result.isSucceed) {
                    hideProgress();
                    swal({
                        type: "success",
                        title: result.Message,
                        text: "Click ok to proceed",
                        customClass: "custom-popup-success",
                    },
                        function (isConfirm) {
                            if (isConfirm) {
                                window.location.href = "@Url.Action("Index", "DocumentCategory")";
                            }
                        }
                    );
                    }
                else {
                    hideProgress();
                    swal("Failed!", result.Message, "error");
                    showValidateMessage(result.Data);
                }
            },
            error: function (err) {
                hideProgress();
                sweetAlert(err.Message, "Something went wrong!", "error");
            }
        });
    });

    $("#btnCancel").click(function (e) {
        e.preventDefault();
        $("#popUp").data("kendoWindow").close();
    });
</script>

DigitalSign.Web/Views/DocumentCategory/Index.cshtml
@using Kendo.Mvc.UI
@model DigitalSign.ViewModels.Master.Document.DocumentCategoryViewModel
@{
    ViewData["Title"] = "Document Category";
}

<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">@ViewData["Title"]</h1>
</div>

<div class="row">
    <div class="col-sm-12 col-md-12">
        <a href="javascript:;" class="btn btn-primary" id="btnCreate" title="Create"><span class="fa fa-plus-circle"></span> Add</a>
        <br />
        <br />

        @using (Html.BeginForm())
        {
            @(Html.Kendo().Grid<DigitalSign.ViewModels.Master.Document.DocumentCategoryViewModel>()
                .Name("grid")
                .Scrollable(s => s.Height("auto"))
                .Columns(columns =>
                {
                    columns.Bound(p => p.ID).Width(125);
                    columns.Bound(p => p.CategoryName).Width(300);
                    columns.Bound(p => p.CategoryDescription).Width(300);
                    columns.Bound("").ClientTemplate("<div class='custom-table-action'>" +
                    "<a data-id='#=ID#' class='btn btn-sm btn-warning edit-action mr-2 k-button k-button-md k-rounded-md k-button-solid' onclick='editDocumentCategory(this)' title='Edit'><i class='fa fa-pencil-alt'></i></a>" +
                    "<a data-id='#=ID#' class='btn btn-sm btn-danger erase-action k-button k-button-md k-rounded-md k-button-solid' onclick='deleteDocumentCategory(this)' title='Edit'><i class='fa fa-trash'></i></a>" +
                    "</div>").Width(150).Title("Action").Filterable(false);
                })
                .Pageable()
                .Sortable()
                .NoRecords(x => x.Template("<div class='empty-grid'>No data</div>"))
                .Filterable()
                .Resizable(re => re.Columns(true))
                .Events(x => x.DataBound("AfterLoad"))
                .DataSource(dataSource => dataSource
                .Ajax()
                .PageSize(10)
                .Read(read => read.Action("GetList", "DocumentCategory"))
                )
                )
        }

    </div>
</div>

<div id="popUp"></div>

<script type="text/javascript">
    $(function () {
        var windowOptions = {
            animation: false,
            modal: true,
            width: 500,
            height: 400,
            visible: false,
            title: 'Create New Document Category'
        };

        //$("#btnCreate").click(Index.Add);
        $("#popUp").kendoWindow(windowOptions);
        $("#frm").kendoValidator().data("kendoValidator");

    });

    function AfterLoad() {
        $("td a").removeClass("k-button");
    };

    function editDocumentCategory(e){
        //e.preventDefault();
        $(".k-window-title").html("Edit Document Category");
        //var dataRow = $(this).attr("data-id");
        var dataRow = e.getAttribute("data-id");
        $("#popUp").data("kendoWindow").refresh({
            url: "@Url.Action("Edit")",
            data: { id: dataRow }
        });
        $("#popUp").data("kendoWindow").center().open();
    };

    function deleteDocumentCategory(e) {
        //e.preventDefault();
        //var dataRow = $(this).attr("data-id");
        var dataRow = e.getAttribute("data-id");
        swal({
            title: "Are you sure?",
            text: "This operation cannot be undone!",
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "Yes, delete it!",
            cancelButtonText: "No, cancel!",
            closeOnConfirm: false,
            closeOnCancel: false
        },

            function (isConfirm) {
                if (isConfirm) {
                    showProgress();
                    console.log(dataRow);
                    $.ajax({
                        type: "POST",
                        data: { id: dataRow },
                        //           async: false,
                        url: "@Url.Action("Delete")",
                        success: function (result) {
                            if (result.isSucceed) {
                                hideProgress();
                                $("#grid").data("kendoGrid").dataSource.read();
                                $("#grid").data("kendoGrid").refresh();
                                swal("Deleted!", "Your file has been deleted", "success");
                            } else {
                                hideProgress();
                                sweetAlert(result.Message, "Something went wrong!", "error");
                            }

                        },
                        error: function (err) {
                            //alert(err.Message);
                            hideProgress();
                            sweetAlert(err.Message, "Something went wrong!", "error");
                        }
                    });
                }
                else {
                    //hideProgress();
                    swal("Cancelled", "", "error");
                }
            });
    }

    $("#btnCreate").click(function(e){
        e.preventDefault();
        $(".k-window-title").html("Create New Document Category");
        $("#popUp").data("kendoWindow").refresh({
            url: "@Url.Action("Create")"
        });
        $("#popUp").data("kendoWindow").center().open();
    });

    function showValidateMessage(validations) {
        for (var validation of validations) {

            let propertyName = validation.PropertyName;
            let errorMessage = validation.ErrorMessage;

            $(`span[data-valmsg-for=${propertyName}]`).text(errorMessage).css("color", "red").css("display", "block");
            console.log(errorMessage + " " + propertyName);
        }
    }
</script>